services:
  app:
    build: app
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SSH_PRIVATE_B64=${SSH_PRIVATE_B64}
      - SSH_PUBLIC=${SSH_PUBLIC}
    ports:
      - "8000:8000"
    restart: unless-stopped
  backup:
    build: backup
    environment:
      - SSH_PUBLIC=${SSH_PUBLIC}
